GET http://localhost:8080/saml/auth?SAMLRequest=nZJdT8IwFIb%2FytJ71g42wGZbghAjCegC0wvvalegsR%2FY04n%2Be8sQw41ceNmT9%2B15nuTkk9bvzEq8twJ89KmVgQK1zlDLQAI1TAugntP1ZLmg%2FZjQvbPecqvQKUyBaXW9wQCE89IaFM1nBeJJmg2ywXiQpdlNSkZpNiIjFD0LByFToFAJQYBWzA14ZnwYkX7SI8NeMqrJkGYpTfsvKJoFYmmY71o77%2FcU4yNNfGDOCDDCx9xqOiZjglmwxE4wpQEvmXtb2K3k%2BOzS1VBU%2FTxvpWmk2V63ej2FgN7XddWrHtc1iiZn06k10Grh1sJ9SC6eVotfQn3gLFaWM9VYzaQJfKSPUZkfGWjn7cr%2F2OT48of8IRDPZ5VVkn9Fd9Zp5v8WSuKkm8imt%2BmitDWwF1xupGiCl1L2MA0LvSjQhikQCJc5vjyd8hs%3D&SigAlg=http%3A%2F%2Fwww.w3.org%2F2000%2F09%2Fxmldsig%23rsa-sha1
Accept: */*
